<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Build info -->
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisMode>Recommended</AnalysisMode>
    <PackAsTool>true</PackAsTool>
    <AssemblyName>shipyard</AssemblyName>
    <ToolCommandName>shipyard</ToolCommandName>

    <!-- Assembly info -->
    <VersionPrefix>0.0.6</VersionPrefix>
    <VersionSuffix>$(SourceRevisionId)</VersionSuffix>
    <Authors>Nickolas Gupton</Authors>
    <RepositoryUrl>https://github.com/CorruptComputer/Shipyard</RepositoryUrl>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <SatelliteResourceLanguages>en-US</SatelliteResourceLanguages>
    <SourceControlInformationFeatureSupported>true</SourceControlInformationFeatureSupported>
    <SourceRevisionId>develop</SourceRevisionId>
    <NoDefaultLaunchSettingsFile>True</NoDefaultLaunchSettingsFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
    <InstallService Condition="$(Configuration) == 'Release'">true</InstallService>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Scriban" Version="7.0.6" />
    <PackageReference Include="System.CommandLine" Version="2.0.5" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
    <None Update="Templates/**/*.scriban">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
